version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./srv:/srv/app
    command: ["fastapi", "run", "app/main.py", "--port", "8080", "--reload"]
    # command: ["ls", "app"]